AWSTemplateFormatVersion: 2010-09-09
Description: Create a VPC Network with subnets, ec2 hosts configured with Security groups and other resources to interact.
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 05da18ae-4592-4c05-9d9d-6de3ed7c042b
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b9c14e01-38d2-47a8-88a8-bb3b20f929f2
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8077d6d1-ceb9-443a-9daf-a7cafd24557e
  JumpBox:
    Type: 'AWS::EC2::Instance'
    Properties: null
    ImageId: ami-0d5eff06f840b45e9
    InstanceType:
      NetworkInterfaces:
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref JumpBoxSG
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b59f0aba-e102-4e45-b965-61601148b971
  AppInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - SubnetId: !Ref PrivateSubnet
        - SubnetId: !Ref PrivateSubnet
        - SubnetId: !Ref PrivateSubnet
        - SubnetId: !Ref PrivateSubnet
        - SubnetId: !Ref PrivateSubnet
        - SubnetId: !Ref PrivateSubnet
        - SubnetId: !Ref PrivateSubnet
        - SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref AppInstanceSG
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c9e020e3-677b-4b11-b524-20372f0f26c9
  JumpBoxSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Join 
        - '-'
        - - JumpBoxSG
      GroupDescription: Allow HTTP/HTTPS and SSH outbound traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: null
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 81a4e7d1-2ce3-453a-85dd-ef8cb50544e2
  AppInstanceSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d892379c-f8e4-4062-8d3e-e12acd347828
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c822d943-5196-4ed0-979a-9373dc1c698a
    DependsOn:
      - NATGateway
  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b0c2b3e4-de7a-4e32-b483-912a6b8746fb
    DependsOn:
      - NATGateway
  NATGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e97fef3e-4331-47e4-9747-26b642195078
